export const plants = [
  "Black Tupelo",
  "Chinese Juniper",
  "Clematis",
  "Common Boxwood",
  "Common Elderberry",
  "Common Lilac",
  "Crab Apple",
  "Crape Myrtle",
  "Dawn Redwood",
  "Dogwood",
  "Eastern Red Cedar",
  "Elderberry",
  "Elm",
  "Frazier Fir",
  "Gardenia",
  "Ginkgo",
  "Hawthorn",
  "Holly",
  "Honey Locust",
  "Horse Chestnut",
  "Hydragea",
  "Juniper",
  "Lilac",
  "Maple (general)",
  "Mockorange",
  "New Jersey Tea",
  "Oaks (general)",
  "Ohio Buckeye",
  "Potentilla",
  "Red Cedar",
  "Red Twig Dogwood",
  "Rhodendron",
  "Roses",
  "Rugosa rose",
  "Saucer magnolia",
  "Serviceberry",
  "Silver Maple",
  "Spirea",
  "Spruce",
  "Sugar Maple",
  "Swamp White Oak",
  "Sweetshrub",
  "Tamarac/Larch",
  "White Fir",
  "White Pine",
  "Willow",
  "Agave",
  "Aster",
  "Astilbe",
  "Big Blue Stem",
  "Bleeding Heart",
  "Butterfly Weed",
  "Cactus",
  "Catmint",
  "Christmas Fern",
  "Coneflower",
  "Daffodil",
  "Dalia",
  "Daylilly",
  "Galllardia",
  "Heaths/Heathers",
  "Hellebores",
  "Hosta",
  "Hyssop",
  "Iris",
  "Ironweed",
  "Jack In Pulpits",
  "Joe-Pye Weed",
  "Lavendar",
  "Lemon Balm",
  "Lily",
  "Lobellia",
  "Lupine",
  "Marigold",
  "Marsh Marigold",
  "May Apple",
  "Meadow Rue",
  "Monarda",
  "Ornamental Grasses",
  "Penstemon",
  "Peony",
  "Petunia",
  "Poppy (general)",
  "Purple Coneflower",
  "Queen of the Prairie",
  "Red Milkweed",
  "Sedges",
  "Sedum",
  "Pansy",
  "Tulip",
  "Violet",
  "Yarrow",
  "Yucca",
  "Zinnia",
  "Apple",
  "Grapes",
  "Fig",
  "Pear",
  "Peach",
  "Pear",
  "Raspberry",
  "Strawberry",
  "Alpine Current",
  "American Filbert",
  "American Holly",
  "Amur Privet",
  "Arborvitae",
  "Azealeas",
  "Bald Cypress",
  "Barberry",
  "Birch",
  "Blackberry",
  "Blueberry",
  "Cranberry",
  "Vegetable",
];
